version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-projeto-integrador
    environment:
      MYSQL_ROOT_PASSWORD: root123  
      MYSQL_DATABASE: projeto_integrador 
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 5s
      timeout: 10s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql  

  api:
    build: .
    container_name: api-projeto-integrador
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root  
      DB_PASSWORD: root123 
      DB_NAME: projeto_integrador
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "sleep 15 && npm run dev" 

volumes:
  mysql_data: